# Generated by Django 3.1.13 on 2021-09-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('voter_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('serial_number', models.IntegerField(blank=True, null=True)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('father_name', models.CharField(blank=True, max_length=100, null=True)),
                ('husband_name', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.SmallIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHER', 'OTHER')], max_length=10, null=True)),
                ('house_number', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
