# Generated by Django 3.2.15 on 2022-09-06 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('polling_station', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('GENERAL', 'GENERAL'), ('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST')], max_length=20)),
                ('related_surnames', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VoterImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('image_url', models.FileField(blank=True, null=True, upload_to='')),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('w', models.IntegerField(default=0)),
                ('h', models.IntegerField(default=0)),
                ('is_cropped', models.BooleanField(default=False)),
                ('is_voter_id_captured', models.BooleanField(default=False)),
                ('is_photo_captured', models.BooleanField(default=False)),
                ('is_serial_captured', models.BooleanField(default=False)),
                ('is_details_captured', models.BooleanField(default=False)),
                ('is_processed', models.BooleanField(default=False)),
                ('has_errors', models.BooleanField(default=False)),
                ('md5_signature', models.CharField(max_length=1000, unique=True)),
                ('station_image', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='voter_images', to='polling_station.pollingstationimage')),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('md5_signature', models.CharField(max_length=1000, unique=True)),
                ('voter_id', models.CharField(blank=True, max_length=20, null=True)),
                ('serial_number', models.IntegerField(blank=True, null=True)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('father_name', models.CharField(blank=True, max_length=100, null=True)),
                ('husband_name', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.SmallIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHER', 'OTHER')], max_length=10, null=True)),
                ('house_number', models.CharField(blank=True, max_length=20, null=True)),
                ('category', models.CharField(blank=True, choices=[('GENERAL', 'GENERAL'), ('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST')], max_length=20, null=True)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('data_eng', models.TextField(blank=True, null=True)),
                ('data_hin', models.TextField(blank=True, null=True)),
                ('caste', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='voters', to='voter.caste')),
                ('polling_booth', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='voters', to='polling_station.pollingstation')),
                ('polling_station_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='voters', to='polling_station.pollingstationimage')),
                ('voter_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='voters', to='voter.voterimage')),
            ],
        ),
    ]
