# Generated by Django 3.1.13 on 2022-08-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voterimage',
            name='h',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='voterimage',
            name='w',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='voterimage',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='voterimage',
            name='y',
            field=models.IntegerField(default=0),
        ),
    ]
