# Generated by Django 3.1.13 on 2021-09-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='data_eng',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='data_hin',
            field=models.TextField(blank=True, null=True),
        ),
    ]
