# Generated by Django 3.1.13 on 2021-09-11 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0002_auto_20210911_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollingBooth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.SmallIntegerField()),
                ('address', models.TextField(blank=True, null=True)),
            ],
        )
    ]
