# Generated by Django 3.1.13 on 2022-08-23 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0002_auto_20220823_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollingstationimage',
            name='is_previewd',
            field=models.BooleanField(default=False),
        ),
    ]
