# Generated by Django 3.1.13 on 2022-08-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0003_pollingstationimage_is_previewd'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollingstationimage',
            name='boxed_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
