# Generated by Django 3.1.13 on 2021-09-11 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('voter', '0004_voter_polling_booth'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollingAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('points', models.IntegerField(default=0)),
                ('polling_booth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='voter.pollingbooth')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
