# Generated by Django 3.1.13 on 2022-08-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0005_voterimage_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollingstationimage',
            name='boxed_image_url',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
