# Generated by Django 3.1.13 on 2022-08-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0006_pollingstationimage_boxed_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='voterimage',
            name='is_cropped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voterimage',
            name='is_details_captured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voterimage',
            name='is_photo_captured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voterimage',
            name='is_serial_captured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voterimage',
            name='is_voter_id_captured',
            field=models.BooleanField(default=False),
        ),
    ]
