# Generated by Django 3.1.13 on 2021-09-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0006_auto_20210911_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollingbooth',
            name='voter_list',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
