# Generated by Django 3.1.13 on 2021-09-11 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0007_pollingbooth_voter_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollingStationImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='VOTER_LIST', max_length=20)),
                ('page_number', models.SmallIntegerField()),
                ('is_processed', models.BooleanField(default=False)),
                ('has_errors', models.BooleanField(default=False)),
                ('x', models.SmallIntegerField()),
                ('y', models.SmallIntegerField()),
                ('h', models.SmallIntegerField()),
                ('w', models.SmallIntegerField()),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='voter.pollingbooth')),
            ],
        ),
        migrations.AddField(
            model_name='voter',
            name='polling_station_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voters', to='voter.pollingstationimage'),
        ),
    ]
