# Generated by Django 3.1.13 on 2022-08-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0008_auto_20220823_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='caste',
            name='category',
            field=models.CharField(choices=[('GENERAL', 'GENERAL'), ('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='caste',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
