# Generated by Django 3.1.13 on 2021-09-12 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0008_auto_20210911_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollingstationimage',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
