# Generated by Django 3.1.13 on 2022-08-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0009_auto_20220823_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollingagent',
            name='mobile',
            field=models.BigIntegerField(blank=True, max_length=10, null=True),
        ),
    ]
