# Generated by Django 3.1.13 on 2022-08-23 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0010_auto_20220823_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='caste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voters', to='voter.caste'),
        ),
    ]
