# Generated by Django 3.1.13 on 2021-09-13 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0010_auto_20210912_0338'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollingbooth',
            name='has_errors',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pollingbooth',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
