# Generated by Django 3.1.13 on 2022-08-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0011_voter_caste'),
    ]

    operations = [
        migrations.AddField(
            model_name='caste',
            name='related_surnames',
            field=models.TextField(default='None'),
            preserve_default=False,
        ),
    ]
