# Generated by Django 3.1.13 on 2021-09-13 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0011_auto_20210913_0449'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollingbooth',
            name='images_created',
            field=models.BooleanField(default=False),
        ),
    ]
