# Generated by Django 3.1.13 on 2022-01-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0013_auto_20220119_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='voterimage',
            name='has_errors',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voterimage',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
