# Generated by Django 3.1.13 on 2022-01-24 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0014_auto_20220121_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='voter_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voters', to='voter.voterimage'),
        ),
    ]
