# Generated by Django 3.1.13 on 2022-01-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0015_voter_voter_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='house_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
