# Generated by Django 3.2.15 on 2022-09-19 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vikaskhand', models.CharField(max_length=100)),
                ('panchayat', models.CharField(max_length=100)),
                ('village_name', models.CharField(max_length=100)),
                ('workd_details', models.TextField()),
                ('amount', models.BigIntegerField(default=0)),
                ('department', models.CharField(max_length=100)),
                ('financial_year', models.SmallIntegerField(default=2000)),
            ],
            options={
                'ordering': ('vikaskhand', 'panchayat', 'financial_year'),
            },
        ),
    ]
