# Generated by Django 3.2.15 on 2022-09-06 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PollingStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.SmallIntegerField()),
                ('address', models.TextField(blank=True, null=True)),
                ('voter_list', models.FileField(blank=True, null=True, upload_to='')),
                ('images_created', models.BooleanField(default=False)),
                ('is_processed', models.BooleanField(default=False)),
                ('has_errors', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='PollingStationImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='VOTER_LIST', max_length=20)),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('boxed_image', models.FileField(blank=True, null=True, upload_to='')),
                ('boxed_image_url', models.FileField(blank=True, null=True, upload_to='')),
                ('page_number', models.SmallIntegerField()),
                ('is_previewd', models.BooleanField(default=False)),
                ('is_processed', models.BooleanField(default=False)),
                ('has_errors', models.BooleanField(default=False)),
                ('md5_signature', models.CharField(max_length=1000, unique=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='images', to='polling_station.pollingstation')),
            ],
        ),
    ]
